name: lint
permissions:
  contents: read
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: install linters
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy
    - name: build debug and lint
      run: |
        ./build.sh debug
        ./build.sh lint
